// Generated by AI | 2026-02-24 | OPA bundle source implementation | implementation_opa_bundles_all_phases.md
package bundlesource

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// BundleManifest represents the .manifest file at the root of an OPA bundle.
type BundleManifest struct {
	Revision string            `json:"revision"`
	Roots    []string          `json:"roots"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// BundleSource implements runtime.PolicySource for OPA bundle directories.
//
// Data loading follows the OPA bundle directory layout: each data.json file is
// placed at the namespace determined by its directory path relative to the bundle
// root. For example, evidra/data/params/data.json maps to data.evidra.data.params.
//
// Only data.json files under a declared bundle root (from .manifest roots) are
// loaded, matching OPA's per-root ownership semantics for single-bundle use.
// YAML data files and multi-bundle root isolation (OPA bundle service semantics)
// are not implemented; use the OPA bundle service if those are required.
type BundleSource struct {
	bundleDir string
	manifest  BundleManifest
}

// NewBundleSource creates a BundleSource from a bundle directory path.
// It validates the .manifest at init time: revision, non-empty roots with valid
// identifiers, and a non-empty profile_name in metadata are all required.
func NewBundleSource(bundleDir string) (*BundleSource, error) {
	manifestPath := filepath.Join(bundleDir, ".manifest")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("read bundle manifest: %w", err)
	}
	var manifest BundleManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("parse bundle manifest: %w", err)
	}
	if manifest.Revision == "" {
		return nil, fmt.Errorf("bundle manifest missing revision")
	}
	if len(manifest.Roots) == 0 {
		return nil, fmt.Errorf("bundle manifest missing roots")
	}
	for _, root := range manifest.Roots {
		if err := validateRootIdentifier(root); err != nil {
			return nil, fmt.Errorf("bundle manifest invalid root %q: %w", root, err)
		}
	}
	if manifest.Metadata["profile_name"] == "" {
		return nil, fmt.Errorf("bundle manifest missing metadata.profile_name")
	}
	return &BundleSource{
		bundleDir: bundleDir,
		manifest:  manifest,
	}, nil
}

// validateRootIdentifier checks that a root is a non-empty lowercase identifier
// (matching OPA data path segment conventions: lowercase, alphanumeric, underscores).
func validateRootIdentifier(root string) error {
	if root == "" {
		return fmt.Errorf("root must not be empty")
	}
	for _, c := range root {
		if !((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_') {
			return fmt.Errorf("root must be lowercase alphanumeric/underscore, got char %q", c)
		}
	}
	return nil
}

// LoadPolicy returns all .rego modules under the bundle directory,
// excluding test files and the tests/ directory.
func (s *BundleSource) LoadPolicy() (map[string][]byte, error) {
	modules := map[string][]byte{}
	err := filepath.WalkDir(s.bundleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "tests" {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".rego" {
			return nil
		}
		if strings.HasSuffix(d.Name(), "_test.rego") {
			return nil
		}
		rel, err := filepath.Rel(s.bundleDir, path)
		if err != nil {
			return err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		modules[filepath.ToSlash(rel)] = content
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(modules) == 0 {
		return nil, fmt.Errorf("bundle contains no policy modules")
	}
	return modules, nil
}

// LoadData returns the merged data from all data.json files under the bundle
// directory, preserving the directory-based namespace structure.
//
// Only data.json files under a declared bundle root are loaded. For example,
// with roots=["evidra"], only data.json files under evidra/ are included.
// This matches OPA's per-root data ownership rule for single-bundle deployments.
func (s *BundleSource) LoadData() ([]byte, error) {
	merged := map[string]interface{}{}
	err := filepath.WalkDir(s.bundleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "tests" {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() != "data.json" {
			return nil
		}
		rel, err := filepath.Rel(s.bundleDir, filepath.Dir(path))
		if err != nil {
			return err
		}
		relSlash := filepath.ToSlash(rel)
		// Only load data.json files that are under a declared root.
		if rel != "." && !isUnderAnyRoot(s.manifest.Roots, relSlash) {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var fileData map[string]interface{}
		if err := json.Unmarshal(content, &fileData); err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		// Place data at the appropriate namespace based on directory path.
		// e.g. evidra/data/params/data.json → merged["evidra"]["data"]["params"] = fileData
		if rel == "." {
			for k, v := range fileData {
				merged[k] = v
			}
		} else {
			parts := strings.Split(relSlash, "/")
			setNested(merged, parts, fileData)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(merged) == 0 {
		return nil, nil
	}
	return json.Marshal(merged)
}

// isUnderAnyRoot reports whether the slash-separated rel path is under at
// least one of the declared bundle roots.
func isUnderAnyRoot(roots []string, rel string) bool {
	for _, root := range roots {
		if rel == root || strings.HasPrefix(rel, root+"/") {
			return true
		}
	}
	return false
}

// setNested places data at a nested map path.
func setNested(root map[string]interface{}, parts []string, data map[string]interface{}) {
	current := root
	for _, part := range parts[:len(parts)-1] {
		next, ok := current[part].(map[string]interface{})
		if !ok {
			next = map[string]interface{}{}
			current[part] = next
		}
		current = next
	}
	last := parts[len(parts)-1]
	existing, ok := current[last].(map[string]interface{})
	if ok {
		for k, v := range data {
			existing[k] = v
		}
	} else {
		current[last] = data
	}
}

// PolicyRef returns the bundle revision as the policy reference.
func (s *BundleSource) PolicyRef() (string, error) {
	return s.manifest.Revision, nil
}

// BundleRevision returns the revision from the bundle manifest.
func (s *BundleSource) BundleRevision() string {
	return s.manifest.Revision
}

// ProfileName returns the profile_name from the bundle manifest metadata.
func (s *BundleSource) ProfileName() string {
	if s.manifest.Metadata == nil {
		return ""
	}
	return s.manifest.Metadata["profile_name"]
}
