// Generated by AI | 2026-02-24 | OPA bundle source tests | implementation_opa_bundles_all_phases.md
package bundlesource_test

import (
	"encoding/json"
	"path/filepath"
	"testing"

	"samebits.com/evidra/pkg/bundlesource"
)

var bundleDir = filepath.Join("..", "..", "policy", "bundles", "ops-v0.1")

func TestNewBundleSource(t *testing.T) {
	bs, err := bundlesource.NewBundleSource(bundleDir)
	if err != nil {
		t.Fatalf("NewBundleSource() error = %v", err)
	}
	if bs.BundleRevision() != "ops-v0.1.0-dev" {
		t.Errorf("BundleRevision() = %q, want ops-v0.1.0-dev", bs.BundleRevision())
	}
	if bs.ProfileName() != "ops-v0.1" {
		t.Errorf("ProfileName() = %q, want ops-v0.1", bs.ProfileName())
	}
}

func TestNewBundleSourceMissingManifest(t *testing.T) {
	_, err := bundlesource.NewBundleSource(t.TempDir())
	if err == nil {
		t.Fatal("expected error for missing .manifest")
	}
}

func TestBundleSourcePolicyRef(t *testing.T) {
	bs, err := bundlesource.NewBundleSource(bundleDir)
	if err != nil {
		t.Fatalf("NewBundleSource() error = %v", err)
	}
	ref, err := bs.PolicyRef()
	if err != nil {
		t.Fatalf("PolicyRef() error = %v", err)
	}
	if ref != "ops-v0.1.0-dev" {
		t.Errorf("PolicyRef() = %q, want ops-v0.1.0-dev", ref)
	}
}

func TestBundleSourceLoadPolicy(t *testing.T) {
	bs, err := bundlesource.NewBundleSource(bundleDir)
	if err != nil {
		t.Fatalf("NewBundleSource() error = %v", err)
	}
	modules, err := bs.LoadPolicy()
	if err != nil {
		t.Fatalf("LoadPolicy() error = %v", err)
	}
	if len(modules) == 0 {
		t.Fatal("expected policy modules, got none")
	}
	// Should include the policy shim and rules
	expectedModules := []string{
		"evidra/policy/policy.rego",
		"evidra/policy/decision.rego",
		"evidra/policy/defaults.rego",
	}
	for _, name := range expectedModules {
		if _, ok := modules[name]; !ok {
			t.Errorf("missing expected module %q", name)
		}
	}
	// Should NOT include test files
	for name := range modules {
		if filepath.Base(name) == "tests" || filepath.Ext(name) == "_test.rego" {
			t.Errorf("test file %q should not be in policy modules", name)
		}
	}
}

func TestBundleSourceLoadData(t *testing.T) {
	bs, err := bundlesource.NewBundleSource(bundleDir)
	if err != nil {
		t.Fatalf("NewBundleSource() error = %v", err)
	}
	data, err := bs.LoadData()
	if err != nil {
		t.Fatalf("LoadData() error = %v", err)
	}
	if data == nil {
		t.Fatal("expected data, got nil")
	}
	var m map[string]interface{}
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("unmarshal data: %v", err)
	}
	// Verify the namespace structure: evidra.data.params
	evidra, ok := m["evidra"].(map[string]interface{})
	if !ok {
		t.Fatal("missing evidra namespace in data")
	}
	dataObj, ok := evidra["data"].(map[string]interface{})
	if !ok {
		t.Fatal("missing evidra.data namespace")
	}
	params, ok := dataObj["params"].(map[string]interface{})
	if !ok {
		t.Fatal("missing evidra.data.params namespace")
	}
	if _, ok := params["ops.mass_delete.max_deletes"]; !ok {
		t.Error("missing ops.mass_delete.max_deletes param")
	}
	hints, ok := dataObj["rule_hints"].(map[string]interface{})
	if !ok {
		t.Fatal("missing evidra.data.rule_hints namespace")
	}
	if _, ok := hints["k8s.protected_namespace"]; !ok {
		t.Error("missing k8s.protected_namespace hint")
	}
}
