// Generated by AI | 2026-02-24 | OPA bundle source implementation | implementation_opa_bundles_all_phases.md
package bundlesource

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// BundleManifest represents the .manifest file at the root of an OPA bundle.
type BundleManifest struct {
	Revision string            `json:"revision"`
	Roots    []string          `json:"roots"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// BundleSource implements runtime.PolicySource for OPA bundle directories.
// It reads policy modules and data files from a standard OPA bundle layout.
type BundleSource struct {
	bundleDir string
	manifest  BundleManifest
}

// NewBundleSource creates a BundleSource from a bundle directory path.
// It validates the .manifest file at init time.
func NewBundleSource(bundleDir string) (*BundleSource, error) {
	manifestPath := filepath.Join(bundleDir, ".manifest")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("read bundle manifest: %w", err)
	}
	var manifest BundleManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("parse bundle manifest: %w", err)
	}
	if manifest.Revision == "" {
		return nil, fmt.Errorf("bundle manifest missing revision")
	}
	if len(manifest.Roots) == 0 {
		return nil, fmt.Errorf("bundle manifest missing roots")
	}
	return &BundleSource{
		bundleDir: bundleDir,
		manifest:  manifest,
	}, nil
}

// LoadPolicy returns all .rego modules under the bundle directory,
// excluding test files.
func (s *BundleSource) LoadPolicy() (map[string][]byte, error) {
	modules := map[string][]byte{}
	err := filepath.WalkDir(s.bundleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "tests" {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".rego" {
			return nil
		}
		if strings.HasSuffix(d.Name(), "_test.rego") {
			return nil
		}
		rel, err := filepath.Rel(s.bundleDir, path)
		if err != nil {
			return err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		modules[filepath.ToSlash(rel)] = content
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(modules) == 0 {
		return nil, fmt.Errorf("bundle contains no policy modules")
	}
	return modules, nil
}

// LoadData returns the merged data from all data.json files under the bundle
// directory, preserving the directory-based namespace structure.
func (s *BundleSource) LoadData() ([]byte, error) {
	merged := map[string]interface{}{}
	err := filepath.WalkDir(s.bundleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "tests" {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() != "data.json" {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(s.bundleDir, filepath.Dir(path))
		if err != nil {
			return err
		}
		var fileData map[string]interface{}
		if err := json.Unmarshal(content, &fileData); err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		// Place data at the appropriate namespace based on directory path.
		// e.g. evidra/data/params/data.json → merged["evidra"]["data"]["params"] = fileData
		if rel == "." {
			for k, v := range fileData {
				merged[k] = v
			}
		} else {
			parts := strings.Split(filepath.ToSlash(rel), "/")
			setNested(merged, parts, fileData)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(merged) == 0 {
		return nil, nil
	}
	return json.Marshal(merged)
}

// setNested places data at a nested map path.
func setNested(root map[string]interface{}, parts []string, data map[string]interface{}) {
	current := root
	for _, part := range parts[:len(parts)-1] {
		next, ok := current[part].(map[string]interface{})
		if !ok {
			next = map[string]interface{}{}
			current[part] = next
		}
		current = next
	}
	last := parts[len(parts)-1]
	existing, ok := current[last].(map[string]interface{})
	if ok {
		for k, v := range data {
			existing[k] = v
		}
	} else {
		current[last] = data
	}
}

// PolicyRef returns the bundle revision as the policy reference.
func (s *BundleSource) PolicyRef() (string, error) {
	return s.manifest.Revision, nil
}

// BundleRevision returns the revision from the bundle manifest.
func (s *BundleSource) BundleRevision() string {
	return s.manifest.Revision
}

// ProfileName returns the profile_name from the bundle manifest metadata.
func (s *BundleSource) ProfileName() string {
	if s.manifest.Metadata == nil {
		return ""
	}
	return s.manifest.Metadata["profile_name"]
}
