// Generated by AI | 2026-02-25 | Zero-config embedded OPA bundle for evidra-mcp | zero-config-embedded-bundle
package evidra

import "embed"

// OpsV01BundleFS is the built-in ops-v0.1 OPA policy bundle, embedded at
// compile time. It enables evidra-mcp to start with no configuration flags.
//
//go:embed all:policy/bundles/ops-v0.1
var OpsV01BundleFS embed.FS
