# Generated by AI | 2026-02-25 | ArgoCD auto-sync in production rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import data.evidra.policy.defaults as defaults

deny["argocd.autosync_prod"] = "Automated sync is denied in this environment" if {
	defaults.resolve_param("argocd.autosync.deny_automated") == true
	action := input.actions[_]
	action.kind == "argocd.sync"
	action.payload.sync_policy.automated == true
}
