# Generated by AI | 2026-02-25 | Privileged container rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import data.evidra.policy.defaults as defaults

deny["k8s.privileged_container"] = "Container has privileged security context" if {
	action := input.actions[_]
	action.kind == "kubectl.apply"
	c := defaults.all_containers(action.payload)[_]
	c.security_context.privileged == true
}
