# Generated by AI | 2026-02-25 | Terraform IAM wildcard Action/Resource rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

deny["terraform.iam_wildcard_policy"] = "IAM policy uses wildcard Action or Resource" if {
	action := input.actions[_]
	action.kind == "terraform.plan"
	stmt := action.payload.iam_policy_statements[_]
	stmt.effect == "Allow"
	iam_stmt_has_wildcard(stmt)
}

iam_stmt_has_wildcard(stmt) if stmt.action == "*"

iam_stmt_has_wildcard(stmt) if stmt.resource == "*"
