# Generated by AI | 2026-02-25 | hostPath volume mount rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

deny["k8s.hostpath_mount"] = "Pod uses hostPath volume mount" if {
	action := input.actions[_]
	action.kind == "kubectl.apply"
	vol := action.payload.volumes[_]
	vol.host_path
}
