# Generated by AI | 2026-02-25 | Run as root rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import data.evidra.policy.defaults as defaults

deny["k8s.run_as_root"] = "Container explicitly runs as root (UID 0)" if {
	defaults.profile_includes_ops
	action := input.actions[_]
	action.kind == "kubectl.apply"
	c := defaults.all_containers(action.payload)[_]
	c.security_context.run_as_user == 0
}
