# Generated by AI | 2026-02-25 | ArgoCD wildcard destination rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

deny["argocd.wildcard_destination"] = "AppProject uses wildcard destination" if {
	action := input.actions[_]
	action.kind == "argocd.project"
	dest := action.payload.destinations[_]
	wildcard_destination(dest)
}

wildcard_destination(dest) if dest.namespace == "*"

wildcard_destination(dest) if dest.server == "*"
