# Generated by AI | 2026-02-25 | S3 missing encryption rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

deny["s3.no_encryption"] = "S3 bucket missing server-side encryption" if {
	action := input.actions[_]
	action.kind == "terraform.plan"
	action.payload.resource_type == "aws_s3_bucket"
	not s3_encryption_enabled(action.payload)
}

s3_encryption_enabled(payload) if {
	payload.server_side_encryption.enabled == true
}
