# Generated by AI | 2026-02-25 | IAM Action:* + Resource:* (effective root) rule | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

deny["aws_iam.wildcard_policy"] = "IAM policy grants Action:* with Resource:* (effective root)" if {
	action := input.actions[_]
	action.kind == "terraform.plan"
	stmt := action.payload.iam_policy_statements[_]
	stmt.effect == "Allow"
	stmt.action == "*"
	stmt.resource == "*"
}
