# Generated by AI | 2026-02-24 | OPA bundle migration — rule ID migration | implementation_opa_bundles_all_phases.md
package evidra.policy

import data.evidra.policy.defaults as defaults

deny["ops.public_exposure"] = msg if {
	defaults.profile_includes_ops
	some i
	action := defaults.actions[i]
	action.kind == "terraform.plan"
	action.payload.publicly_exposed == true
	not defaults.has_tag(action, "approved_public")
	msg := "Public exposure requires approved_public"
}
