# Generated by AI | 2026-02-24 | OPA bundle migration — rule ID migration | implementation_opa_bundles_all_phases.md
package evidra.policy

import data.evidra.policy.defaults as defaults

warn["ops.breakglass_used"] = "breakglass tag present" if {
	action := defaults.actions[_]
	action.risk_tags[_] == "breakglass"
}
