# Generated by AI | 2026-02-24 | OPA bundle migration — rule ID migration | implementation_opa_bundles_all_phases.md
package evidra.policy

warn["ops.autonomous_execution"] = msg if {
	input.actor.type == "agent"
	input.source == "mcp"
	msg := "Autonomous execution: agent via mcp"
}
