# Generated by AI | 2026-02-24 | OPA bundle migration — rule ID migration | implementation_opa_bundles_all_phases.md
package evidra.policy

import data.evidra.policy.defaults as defaults

warn["ops.autonomous_execution"] = msg if {
	defaults.actor_type == "agent"
	defaults.actor_origin == "mcp"
	msg := "Autonomous execution: agent via mcp"
}
