// Generated by AI | 2026-02-25 | End-to-end MCP validate test via run() with embedded bundle | verify_p0
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"strings"
	"testing"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"samebits.com/evidra/pkg/mcpserver"
)

// inMemServer wraps *mcp.Server and replaces the mcp.StdioTransport that
// run() injects with the provided in-memory transport. This lets run() be
// exercised end-to-end — including bundle extraction, policy loading, and
// evidence wiring — without touching os.Stdin / os.Stdout.
type inMemServer struct {
	real    *mcp.Server
	serverT mcp.Transport
}

func (s *inMemServer) Run(ctx context.Context, _ mcp.Transport) error {
	return s.real.Run(ctx, s.serverT)
}

// TestMCPValidate_PassThenDeny_UsesEmbeddedBundle calls run() with no bundle
// flags, exercises the validate MCP tool with a PASS and a DENY call over an
// in-memory transport, and asserts:
//   - stderr carries "using built-in ops-v0.1 bundle"
//   - PASS response: allow=true
//   - DENY response: allow=false, at least one rule_id/reason, at least one hint
func TestMCPValidate_PassThenDeny_UsesEmbeddedBundle(t *testing.T) {
	old := newServerFunc
	defer func() { newServerFunc = old }()

	t.Setenv("EVIDRA_BUNDLE_PATH", "")
	t.Setenv("EVIDRA_POLICY_PATH", "")
	t.Setenv("EVIDRA_DATA_PATH", "")

	clientT, serverT := mcp.NewInMemoryTransports()

	newServerFunc = func(opts mcpserver.Options) serverRunner {
		return &inMemServer{real: mcpserver.NewServer(opts), serverT: serverT}
	}

	var errOut bytes.Buffer
	serverDone := make(chan struct{})
	go func() {
		defer close(serverDone)
		run([]string{"--evidence-dir", t.TempDir()}, io.Discard, &errOut)
	}()

	// Safety net: if the test exits early (e.g. t.Fatalf before cs.Close),
	// the cleanup ensures we wait for the server goroutine to exit.
	t.Cleanup(func() {
		select {
		case <-serverDone:
		case <-time.After(3 * time.Second):
			t.Error("server goroutine did not exit within 3s")
		}
	})

	ctx := context.Background()
	client := mcp.NewClient(&mcp.Implementation{Name: "test-client", Version: "0.1"}, nil)
	cs, err := client.Connect(ctx, clientT, nil)
	if err != nil {
		t.Fatalf("client connect: %v", err)
	}

	// ── PASS: kubectl get — safe operation ───────────────────────────────
	t.Run("pass", func(t *testing.T) {
		result, err := cs.CallTool(ctx, &mcp.CallToolParams{
			Name: "validate",
			Arguments: map[string]any{
				"actor":     map[string]any{"type": "human", "id": "tester", "origin": "cli"},
				"tool":      "kubectl",
				"operation": "get",
				"params":    map[string]any{},
				"context":   map[string]any{},
			},
		})
		if err != nil {
			t.Fatalf("CallTool: %v", err)
		}
		out := parseMCPValidateOut(t, result)
		if !out.Policy.Allow {
			t.Errorf("allow=false want true; reasons=%v rule_ids=%v", out.Reasons, out.RuleIDs)
		}
	})

	// ── DENY: kubectl delete kube-system — protected namespace ───────────
	t.Run("deny", func(t *testing.T) {
		result, err := cs.CallTool(ctx, &mcp.CallToolParams{
			Name: "validate",
			Arguments: map[string]any{
				"actor":     map[string]any{"type": "human", "id": "tester", "origin": "cli"},
				"tool":      "kubectl",
				"operation": "delete",
				"params":    map[string]any{"payload": map[string]any{"namespace": "kube-system"}},
				"context":   map[string]any{},
			},
		})
		if err != nil {
			t.Fatalf("CallTool: %v", err)
		}
		out := parseMCPValidateOut(t, result)
		if out.Policy.Allow {
			t.Error("allow=true want false")
		}
		if len(out.RuleIDs) == 0 && len(out.Reasons) == 0 {
			t.Error("expected at least one rule_id or reason")
		}
		if len(out.Hints) == 0 {
			t.Error("expected at least one hint")
		}
	})

	// Close client to trigger server shutdown, then verify stderr.
	cs.Close()
	select {
	case <-serverDone:
	case <-time.After(3 * time.Second):
		t.Fatal("server did not stop within 3s after client close")
	}
	if !strings.Contains(errOut.String(), "using built-in ops-v0.1 bundle") {
		t.Errorf("stderr missing embedded bundle notice; got:\n%s", errOut.String())
	}
}

// parseMCPValidateOut extracts mcpserver.ValidateOutput from a CallToolResult.
// Mirrors parseValidateOutput in cmd/evidra-mcp/test/zeroconfig_integration_test.go
// for use within package main tests.
func parseMCPValidateOut(t *testing.T, result *mcp.CallToolResult) mcpserver.ValidateOutput {
	t.Helper()
	if result.StructuredContent != nil {
		b, err := json.Marshal(result.StructuredContent)
		if err != nil {
			t.Fatalf("marshal StructuredContent: %v", err)
		}
		var out mcpserver.ValidateOutput
		if err := json.Unmarshal(b, &out); err != nil {
			t.Fatalf("unmarshal ValidateOutput: %v", err)
		}
		return out
	}
	for _, c := range result.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			var out mcpserver.ValidateOutput
			if err := json.Unmarshal([]byte(tc.Text), &out); err != nil {
				t.Fatalf("unmarshal ValidateOutput from TextContent: %v", err)
			}
			return out
		}
	}
	t.Fatal("no parseable ValidateOutput in CallToolResult")
	return mcpserver.ValidateOutput{}
}
