// Generated by AI | 2026-02-25 | Stdio integration test for evidra-mcp zero-config | P0-homebrew-release
package evidramcp_test

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// testBinary is the path to the compiled evidra-mcp binary, built once in
// TestMain and shared across all tests in this package.
var testBinary string

func TestMain(m *testing.M) {
	dir, err := os.MkdirTemp("", "evidra-mcp-bin-*")
	if err != nil {
		fmt.Fprintf(os.Stderr, "create temp dir: %v\n", err)
		os.Exit(1)
	}
	testBinary = filepath.Join(dir, "evidra-mcp")

	build := exec.Command("go", "build", "-o", testBinary, "../")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "build evidra-mcp: %v\n", err)
		os.RemoveAll(dir)
		os.Exit(1)
	}

	code := m.Run()
	os.RemoveAll(dir)
	os.Exit(code)
}

// TestStdioZeroConfig starts evidra-mcp as a child process with no --bundle
// flag and no EVIDRA_BUNDLE_PATH env var, then sends two MCP tool calls over
// stdio and asserts end-to-end policy evaluation with the embedded bundle.
//
// Fixtures are loaded from testdata/ (shared with the Docker smoke tests):
//   - testdata/init.jsonl          — MCP handshake (id:1 + initialized notification)
//   - testdata/validate_pass.jsonl — safe kubectl get (id:2)
//   - testdata/validate_deny.jsonl — delete in kube-system (id:2, remapped to id:3)
//
// The test reads responses from stdout before closing stdin, avoiding a race
// where EOF cancels in-flight handlers in the MCP transport.
func TestStdioZeroConfig(t *testing.T) {
	if testBinary == "" {
		t.Fatal("test binary not built")
	}

	// Load shared fixtures.
	initLines := readFixture(t, "testdata/init.jsonl")
	passLines := readFixture(t, "testdata/validate_pass.jsonl")
	denyLines := readFixture(t, "testdata/validate_deny.jsonl")

	// Both pass and deny fixtures use "id":2. Remap deny to "id":3 so both
	// tool calls can coexist in a single MCP session.
	for i, line := range denyLines {
		denyLines[i] = strings.Replace(line, `"id":2`, `"id":3`, 1)
	}

	var messages []string
	messages = append(messages, initLines...)
	messages = append(messages, passLines...)
	messages = append(messages, denyLines...)

	evidenceDir := t.TempDir()

	cmd := exec.Command(testBinary, "--evidence-dir", evidenceDir)
	// Strip env vars that would override the embedded bundle fallback.
	cmd.Env = stripEnvKeys(os.Environ(),
		"EVIDRA_BUNDLE_PATH",
		"EVIDRA_POLICY_PATH",
		"EVIDRA_DATA_PATH",
	)

	stdin, err := cmd.StdinPipe()
	if err != nil {
		t.Fatalf("stdin pipe: %v", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatalf("stdout pipe: %v", err)
	}
	var stderrBuf strings.Builder
	cmd.Stderr = &stderrBuf

	if err := cmd.Start(); err != nil {
		t.Fatalf("start process: %v", err)
	}

	// Kill the process if the test hangs.
	done := make(chan struct{})
	go func() {
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			cmd.Process.Kill()
		}
	}()
	defer close(done)

	// Send all messages to stdin.
	for _, msg := range messages {
		if _, err := fmt.Fprintln(stdin, msg); err != nil {
			t.Fatalf("write to stdin: %v", err)
		}
	}

	// Read stdout until we have both tool-call responses (id:2 and id:3).
	// This avoids closing stdin prematurely — an early EOF would trigger
	// transport shutdown that cancels in-flight handlers.
	type readResult struct {
		msgs []jsonrpcMsg
		err  error
	}
	ch := make(chan readResult, 1)
	go func() {
		var msgs []jsonrpcMsg
		scanner := bufio.NewScanner(stdout)
		scanner.Buffer(make([]byte, 256*1024), 256*1024)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" {
				continue
			}
			var msg jsonrpcMsg
			if json.Unmarshal([]byte(line), &msg) != nil {
				continue
			}
			if msg.JSONRPC == "2.0" {
				msgs = append(msgs, msg)
			}
			// Stop reading once we have both expected tool responses.
			got2, got3 := false, false
			for _, m := range msgs {
				switch rpcID(m) {
				case 2:
					got2 = true
				case 3:
					got3 = true
				}
			}
			if got2 && got3 {
				break
			}
		}
		ch <- readResult{msgs: msgs, err: scanner.Err()}
	}()

	var responses []jsonrpcMsg
	select {
	case r := <-ch:
		responses = r.msgs
		if r.err != nil {
			t.Fatalf("read stdout: %v", r.err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("timeout waiting for tool responses")
	}

	// Now safe to close stdin and let the server shut down.
	stdin.Close()
	_ = cmd.Wait()

	// ── Assert stderr contains embedded bundle notice ────────────
	stderrStr := stderrBuf.String()
	if !strings.Contains(stderrStr, "using built-in ops-v0.1 bundle") {
		t.Errorf("stderr missing embedded bundle notice:\n%s", stderrStr)
	}

	// Index responses by JSON-RPC id.
	byID := make(map[int]jsonrpcMsg, len(responses))
	for _, r := range responses {
		byID[rpcID(r)] = r
	}

	// ── PASS case (id:2): safe kubectl get ───────────────────────
	t.Run("pass", func(t *testing.T) {
		msg, ok := byID[2]
		if !ok {
			t.Fatal("no response for id:2")
		}
		assertNoRPCError(t, msg)
		out := unmarshalValidateResult(t, msg)
		if !out.Policy.Allow {
			t.Errorf("expected allow=true, got false (risk_level=%s, reasons=%v)",
				out.Policy.RiskLevel, out.Reasons)
		}
	})

	// ── DENY case (id:3): delete in kube-system ──────────────────
	t.Run("deny", func(t *testing.T) {
		msg, ok := byID[3]
		if !ok {
			t.Fatal("no response for id:3")
		}
		assertNoRPCError(t, msg)
		out := unmarshalValidateResult(t, msg)
		if out.Policy.Allow {
			t.Error("expected allow=false, got true")
		}
		if out.Policy.RiskLevel != "high" {
			t.Errorf("expected risk_level=high, got %q", out.Policy.RiskLevel)
		}
		if len(out.RuleIDs) == 0 && len(out.Reasons) == 0 {
			t.Error("expected at least one rule_id or reason")
		}
		if len(out.Hints) == 0 {
			t.Error("expected at least one hint")
		}
		if out.EventID == "" {
			t.Error("expected non-empty event_id")
		}
	})
}

// ── JSON-RPC / MCP wire types ────────────────────────────────────────

type jsonrpcMsg struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      json.RawMessage `json:"id,omitempty"`
	Method  string          `json:"method,omitempty"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   json.RawMessage `json:"error,omitempty"`
}

type mcpToolResult struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content,omitempty"`
	StructuredContent json.RawMessage `json:"structuredContent,omitempty"`
}

// stdioValidateOutput mirrors mcpserver.ValidateOutput with only the fields
// needed for assertions. Defined locally to avoid importing the server package
// into the child-process test.
type stdioValidateOutput struct {
	OK      bool   `json:"ok"`
	EventID string `json:"event_id"`
	Policy  struct {
		Allow     bool   `json:"allow"`
		RiskLevel string `json:"risk_level"`
	} `json:"policy"`
	RuleIDs []string `json:"rule_ids"`
	Hints   []string `json:"hints"`
	Reasons []string `json:"reasons"`
}

// ── Helpers ──────────────────────────────────────────────────────────

// readFixture reads non-empty lines from a file relative to the test directory.
func readFixture(t *testing.T, path string) []string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture %s: %v", path, err)
	}
	var lines []string
	for _, line := range strings.Split(string(data), "\n") {
		if s := strings.TrimSpace(line); s != "" {
			lines = append(lines, s)
		}
	}
	return lines
}

// rpcID extracts the numeric id from a JSON-RPC message. Returns -1 for
// notifications or unparseable ids.
func rpcID(msg jsonrpcMsg) int {
	var id float64
	if json.Unmarshal(msg.ID, &id) == nil {
		return int(id)
	}
	return -1
}

// assertNoRPCError fails the test if the JSON-RPC response carries an error.
func assertNoRPCError(t *testing.T, msg jsonrpcMsg) {
	t.Helper()
	if len(msg.Error) > 0 && string(msg.Error) != "null" {
		t.Fatalf("unexpected JSON-RPC error: %s", msg.Error)
	}
}

// unmarshalValidateResult extracts stdioValidateOutput from a tools/call
// JSON-RPC response. Handles both StructuredContent and TextContent formats.
func unmarshalValidateResult(t *testing.T, msg jsonrpcMsg) stdioValidateOutput {
	t.Helper()

	var tr mcpToolResult
	if err := json.Unmarshal(msg.Result, &tr); err != nil {
		t.Fatalf("unmarshal tool result: %v\nraw: %s", err, msg.Result)
	}

	var out stdioValidateOutput
	switch {
	case len(tr.StructuredContent) > 0 && string(tr.StructuredContent) != "null":
		if err := json.Unmarshal(tr.StructuredContent, &out); err != nil {
			t.Fatalf("unmarshal structured content: %v", err)
		}
	case len(tr.Content) > 0 && tr.Content[0].Type == "text":
		if err := json.Unmarshal([]byte(tr.Content[0].Text), &out); err != nil {
			t.Fatalf("unmarshal text content: %v\nraw: %s", err, tr.Content[0].Text)
		}
	default:
		t.Fatalf("no parseable content in tool result: %s", msg.Result)
	}
	return out
}

// stripEnvKeys returns a copy of env with any entries whose key matches
// one of the given names removed.
func stripEnvKeys(env []string, keys ...string) []string {
	out := make([]string, 0, len(env))
	for _, e := range env {
		skip := false
		for _, k := range keys {
			if strings.HasPrefix(e, k+"=") {
				skip = true
				break
			}
		}
		if !skip {
			out = append(out, e)
		}
	}
	return out
}
