// Generated by AI | 2026-02-25 | Zero-config integration test (external package) | zero-config-embedded-bundle
package evidramcp_test

import (
	"context"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	evidra "samebits.com/evidra"
	"samebits.com/evidra/pkg/mcpserver"
)

// TestEmbeddedBundleZeroConfig verifies that the embedded ops-v0.1 bundle
// loads correctly and produces deterministic policy decisions.
//
// This test exercises the full MCP call path — server construction, in-memory
// transport, tool dispatch, OPA evaluation — without invoking run() or touching
// any file paths outside of t.TempDir().
func TestEmbeddedBundleZeroConfig(t *testing.T) {
	bundleDir := extractEmbeddedBundle(t)

	server := mcpserver.NewServer(mcpserver.Options{
		BundlePath:   bundleDir,
		EvidencePath: t.TempDir(),
		Mode:         mcpserver.ModeEnforce,
	})

	ctx := context.Background()
	clientT, serverT := mcp.NewInMemoryTransports()

	serverSession, err := server.Connect(ctx, serverT, nil)
	if err != nil {
		t.Fatalf("server connect: %v", err)
	}
	defer serverSession.Close()

	client := mcp.NewClient(&mcp.Implementation{Name: "test-client", Version: "0.0.1"}, nil)
	clientSession, err := client.Connect(ctx, clientT, nil)
	if err != nil {
		t.Fatalf("client connect: %v", err)
	}
	defer clientSession.Close()

	cases := []struct {
		name       string
		args       map[string]any
		wantAllow  bool
		wantRuleID string // required on deny; empty = not checked
		wantHints  bool
	}{
		{
			name: "safe_get_is_allowed",
			args: map[string]any{
				"actor":     map[string]any{"type": "human", "id": "tester", "origin": "cli"},
				"tool":      "kubectl",
				"operation": "get",
				"params":    map[string]any{},
				"context":   map[string]any{},
			},
			wantAllow: true,
		},
		{
			name: "delete_protected_namespace_is_denied",
			args: map[string]any{
				"actor":     map[string]any{"type": "human", "id": "tester", "origin": "cli"},
				"tool":      "kubectl",
				"operation": "delete",
				"params":    map[string]any{"payload": map[string]any{"namespace": "prod"}},
				"context":   map[string]any{},
			},
			wantAllow:  false,
			wantRuleID: "ops.unapproved_change",
			wantHints:  true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			result, err := clientSession.CallTool(ctx, &mcp.CallToolParams{
				Name:      "validate",
				Arguments: tc.args,
			})
			if err != nil {
				t.Fatalf("CallTool: %v", err)
			}
			if result.IsError {
				t.Fatalf("tool returned IsError=true; content: %+v", result.Content)
			}

			out := parseValidateOutput(t, result)

			if out.Policy.Allow != tc.wantAllow {
				t.Errorf("allow=%v want %v; reasons=%v rule_ids=%v",
					out.Policy.Allow, tc.wantAllow, out.Reasons, out.RuleIDs)
			}
			if tc.wantRuleID != "" && !contains(out.RuleIDs, tc.wantRuleID) {
				t.Errorf("rule_ids=%v, want %q present", out.RuleIDs, tc.wantRuleID)
			}
			if tc.wantHints && len(out.Hints) == 0 {
				t.Errorf("expected at least one hint, got none")
			}
			if out.EventID == "" {
				t.Errorf("expected non-empty event_id")
			}
		})
	}
}

// extractEmbeddedBundle extracts evidra.OpsV01BundleFS into t.TempDir()
// and returns the path. Cleanup is handled by the test framework.
func extractEmbeddedBundle(t *testing.T) string {
	t.Helper()
	const root = "policy/bundles/ops-v0.1"
	dir := t.TempDir()
	err := fs.WalkDir(evidra.OpsV01BundleFS, root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || path == root {
			return err
		}
		dst := filepath.Join(dir, filepath.FromSlash(strings.TrimPrefix(path, root+"/")))
		if d.IsDir() {
			return os.MkdirAll(dst, 0o755)
		}
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		data, err := evidra.OpsV01BundleFS.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(dst, data, 0o644)
	})
	if err != nil {
		t.Fatalf("extract embedded bundle: %v", err)
	}
	return dir
}

func parseValidateOutput(t *testing.T, result *mcp.CallToolResult) mcpserver.ValidateOutput {
	t.Helper()
	if result.StructuredContent != nil {
		b, err := json.Marshal(result.StructuredContent)
		if err != nil {
			t.Fatalf("marshal StructuredContent: %v", err)
		}
		var out mcpserver.ValidateOutput
		if err := json.Unmarshal(b, &out); err != nil {
			t.Fatalf("unmarshal ValidateOutput: %v", err)
		}
		return out
	}
	for _, c := range result.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			var out mcpserver.ValidateOutput
			if err := json.Unmarshal([]byte(tc.Text), &out); err != nil {
				t.Fatalf("unmarshal ValidateOutput from TextContent: %v", err)
			}
			return out
		}
	}
	t.Fatal("no parseable ValidateOutput in CallToolResult")
	return mcpserver.ValidateOutput{}
}

func contains(slice []string, s string) bool {
	for _, v := range slice {
		if v == s {
			return true
		}
	}
	return false
}
