package invocation

import (
	"errors"
	"fmt"
)

// Canonical keys for ToolInvocation.Params and ToolInvocation.Context.
const (
	KeyTarget     = "target"
	KeyPayload    = "payload"
	KeyRiskTags   = "risk_tags"
	KeyScenarioID = "scenario_id"
	KeySource     = "source"
	KeyIntent     = "intent"
)

// Generated by AI | 2026-02-24 | TD-07: allowed key sets for strict validation | Related AI prompt file: ai/AI_PROMPTS_LOG.md
var allowedParamKeys = map[string]bool{
	KeyTarget: true, KeyPayload: true, KeyRiskTags: true, KeyScenarioID: true,
}
var allowedContextKeys = map[string]bool{
	KeySource: true, KeyIntent: true, KeyScenarioID: true, "environment": true,
}

type Actor struct {
	Type   string `json:"type"`
	ID     string `json:"id"`
	Origin string `json:"origin"`
}

type ToolInvocation struct {
	Actor       Actor                  `json:"actor"`
	Tool        string                 `json:"tool"`
	Operation   string                 `json:"operation"`
	Params      map[string]interface{} `json:"params"`
	Context     map[string]interface{} `json:"context"`
	Environment string                 `json:"environment,omitempty"`
}

func (ti *ToolInvocation) ValidateStructure() error {
	if ti.Actor.Type == "" {
		return errors.New("actor.type is required")
	}
	if ti.Actor.ID == "" {
		return errors.New("actor.id is required")
	}
	if ti.Actor.Origin == "" {
		return errors.New("actor.origin is required")
	}
	if ti.Tool == "" {
		return errors.New("tool is required")
	}
	if ti.Operation == "" {
		return errors.New("operation is required")
	}
	if ti.Params == nil {
		return errors.New("params is required")
	}

	if err := validateMap(ti.Params, KeyTarget); err != nil {
		return err
	}
	if err := validateMap(ti.Params, KeyPayload); err != nil {
		return err
	}
	if err := validateRiskTags(ti.Params[KeyRiskTags]); err != nil {
		return err
	}

	if err := rejectUnknownKeys(ti.Params, allowedParamKeys, "params"); err != nil {
		return err
	}
	if ti.Context != nil {
		if err := rejectUnknownKeys(ti.Context, allowedContextKeys, "context"); err != nil {
			return err
		}
	}

	return nil
}

// Generated by AI | 2026-02-24 | TD-07: reject unknown keys in Params/Context maps | Related AI prompt file: ai/AI_PROMPTS_LOG.md
func rejectUnknownKeys(m map[string]interface{}, allowed map[string]bool, section string) error {
	for k := range m {
		if !allowed[k] {
			return fmt.Errorf("unknown %s key: %q", section, k)
		}
	}
	return nil
}

// Generated by AI
// Date: 2026-02-23
// Purpose: Validates that a parameter is a JSON object if present.
// Related AI prompt file: ai/AI_PROMPTS_LOG.md
func validateMap(params map[string]interface{}, key string) error {
	val, ok := params[key]
	if !ok || val == nil {
		return nil
	}
	if _, isMap := val.(map[string]interface{}); !isMap {
		return fmt.Errorf("field '%s' must be a JSON object", key)
	}
	return nil
}

// Generated by AI
// Date: 2026-02-23
// Purpose: Validates that risk_tags is a slice of strings if present.
// Related AI prompt file: ai/AI_PROMPTS_LOG.md
func validateRiskTags(val interface{}) error {
	if val == nil {
		return nil
	}

	switch v := val.(type) {
	case []string:
		return nil
	case []interface{}:
		for _, entry := range v {
			if _, ok := entry.(string); !ok {
				return errors.New("field 'risk_tags' must be a list of strings")
			}
		}
		return nil
	default:
		return errors.New("field 'risk_tags' must be a list of strings")
	}
}
