# Generated by AI | 2026-02-24 | OPA bundle migration — decision contract tests | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_decision_contract if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",

		"actions": [
			{
				"kind": "k8s.apply",
				"target": "kube-system",
				"risk_tags": [],
				"payload": {"namespace": "kube-system"},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	d.risk_level == "high"
	count(d.reasons) == 1
	d.reason == "Changes in restricted namespace require breakglass"
	"k8s.protected_namespace" in d.hits
	"Add risk_tag: breakglass" in d.hints
}

test_allowed_operation_reason if {
	payload := {
		"tool": "kubectl",
		"operation": "get",
		"environment": "dev",

		"actions": [
			{
				"kind": "kubectl.get",
				"target": "default",
				"risk_tags": [],
				"payload": {"namespace": "default"},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	d.risk_level == "low"
	d.reason == "ok"
	count(d.reasons) == 0
}

test_hints_dedup if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",

		"actions": [
			{
				"kind": "kubectl.delete",
				"target": "default",
				"risk_tags": [],
				"payload": {"resource_count": 10, "namespace": "default"},
			},
			{
				"kind": "terraform.plan",
				"target": "default",
				"risk_tags": [],
				"payload": {"destroy_count": 8},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	count(d.hints) == 2
	some idx1
	d.hints[idx1] == "Reduce deletion scope"
	some idx2
	d.hints[idx2] == "Or add risk_tag: breakglass"
}

test_risk_high_with_breakglass_tag if {
	payload := {
		"tool": "kubectl",
		"operation": "get",
		"environment": "dev",

		"actions": [
			{
				"kind": "kubectl.get",
				"target": "default",
				"risk_tags": ["breakglass"],
				"payload": {"namespace": "default"},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	d.risk_level == "medium"
	d.reason == "ok"
}
