# Generated by AI | 2026-02-25 | Tests for k8s.hostpath_mount | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_hostpath_mount if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "kubectl.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25"}],
				"init_containers": [],
				"volumes": [{"name": "host-vol", "host_path": {"path": "/"}}],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.hostpath_mount" in d.hits
}

test_allow_pvc_volume if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "kubectl.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25"}],
				"init_containers": [],
				"volumes": [{"name": "data", "persistent_volume_claim": {"claim_name": "my-pvc"}}],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
