# Generated by AI | 2026-02-24 | OPA bundle migration — deny kube-system test | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_deny_kube_system_without_breakglass if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [
			{
				"kind": "kubectl.apply",
				"target": "kube-system",
				"risk_tags": [],
				"payload": {"namespace": "kube-system"},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	d.reason == "Changes in restricted namespace require breakglass"
	"k8s.protected_namespace" in d.hits
	"Add risk_tag: breakglass" in d.hints
}
