# Generated by AI | 2026-02-25 | Tests for s3.no_versioning_prod | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_s3_no_versioning_in_production if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "production",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {
				"resource_type": "aws_s3_bucket",
				"versioning": {"enabled": false},
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"aws_s3.no_versioning_prod" in d.hits
}

test_allow_s3_no_versioning_in_dev if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {
				"resource_type": "aws_s3_bucket",
				"versioning": {"enabled": false},
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not "aws_s3.no_versioning_prod" in d.hits
}

test_allow_s3_with_versioning_in_production if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "production",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {
				"resource_type": "aws_s3_bucket",
				"versioning": {"enabled": true},
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not "aws_s3.no_versioning_prod" in d.hits
}
