# Generated by AI | 2026-02-25 | Tests for terraform.s3_public_access | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_s3_missing_public_access_block if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"resource_type": "aws_s3_bucket"},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"terraform.s3_public_access" in d.hits
}

test_deny_s3_incomplete_public_access_block if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {
				"resource_type": "aws_s3_bucket",
				"s3_public_access_block": {
					"block_public_acls": true,
					"ignore_public_acls": true,
					"block_public_policy": false,
					"restrict_public_buckets": true,
				},
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"terraform.s3_public_access" in d.hits
}

test_allow_s3_complete_public_access_block if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {
				"resource_type": "aws_s3_bucket",
				"s3_public_access_block": {
					"block_public_acls": true,
					"ignore_public_acls": true,
					"block_public_policy": true,
					"restrict_public_buckets": true,
				},
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not "terraform.s3_public_access" in d.hits
}

test_allow_s3_approved_public if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": ["approved_public"],
			"payload": {"resource_type": "aws_s3_bucket"},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not "terraform.s3_public_access" in d.hits
}
