# Generated by AI | 2026-02-24 | OPA bundle migration — deny prod test | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_deny_prod_without_change_approved if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "prod",
		"actions": [
			{
				"kind": "kubectl.apply",
				"target": "prod",
				"risk_tags": [],
				"payload": {"namespace": "prod"},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	d.reason == "Production changes require change-approved"
	"ops.unapproved_change" in d.hits
}
