# Generated by AI | 2026-02-24 | OPA bundle migration — deny public exposure test | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_deny_public_exposure_without_approval if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"context": {"environment": "dev"},
		"actions": [
			{
				"kind": "terraform.plan",
				"target": "infra",
				"risk_tags": [],
				"payload": {"publicly_exposed": true},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	d.reason == "Public exposure requires approved_public"
	"ops.public_exposure" in d.hits
}
