# Generated by AI | 2026-02-25 | Tests for k8s.privileged_container | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_privileged_container if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"privileged": true}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.privileged_container" in d.hits
}

test_deny_privileged_init_container if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"privileged": false}}],
				"init_containers": [{"name": "init", "image": "busybox:1.36", "security_context": {"privileged": true}}],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.privileged_container" in d.hits
}

test_allow_unprivileged_container if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"privileged": false}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
