# Generated by AI | 2026-02-25 | Tests for k8s.dangerous_capabilities | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_sys_admin_capability if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"capabilities": {"add": ["SYS_ADMIN"]}}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.dangerous_capabilities" in d.hits
}

test_deny_net_raw_capability if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"capabilities": {"add": ["NET_RAW"]}}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.dangerous_capabilities" in d.hits
}

test_allow_safe_capabilities if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"capabilities": {"add": ["NET_BIND_SERVICE"], "drop": ["ALL"]}}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
