# Generated by AI | 2026-02-25 | Tests for argocd.dangerous_sync_combo | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_dangerous_sync_combo_in_production if {
	payload := {
		"tool": "argocd",
		"operation": "sync",
		"environment": "production",
		"actions": [{
			"kind": "argocd.sync",
			"target": "my-app",
			"risk_tags": [],
			"payload": {"sync_policy": {"automated": {"prune": true, "self_heal": true}}},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"argocd.dangerous_sync_combo" in d.hits
}

test_allow_dangerous_sync_combo_in_dev if {
	payload := {
		"tool": "argocd",
		"operation": "sync",
		"environment": "dev",
		"actions": [{
			"kind": "argocd.sync",
			"target": "my-app",
			"risk_tags": [],
			"payload": {"sync_policy": {"automated": {"prune": true, "self_heal": true}}},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}

test_allow_prune_without_self_heal_in_production if {
	payload := {
		"tool": "argocd",
		"operation": "sync",
		"environment": "production",
		"actions": [{
			"kind": "argocd.sync",
			"target": "my-app",
			"risk_tags": [],
			"payload": {"sync_policy": {"automated": {"prune": true, "self_heal": false}}},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
