# Generated by AI | 2026-02-25 | Tests for argocd.wildcard_destination | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_wildcard_namespace if {
	payload := {
		"tool": "argocd",
		"operation": "project",
		"environment": "dev",
		"actions": [{
			"kind": "argocd.project",
			"target": "default",
			"risk_tags": [],
			"payload": {"destinations": [{"namespace": "*", "server": "https://kubernetes.default.svc"}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"argocd.wildcard_destination" in d.hits
}

test_deny_wildcard_server if {
	payload := {
		"tool": "argocd",
		"operation": "project",
		"environment": "dev",
		"actions": [{
			"kind": "argocd.project",
			"target": "default",
			"risk_tags": [],
			"payload": {"destinations": [{"namespace": "prod", "server": "*"}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"argocd.wildcard_destination" in d.hits
}

test_allow_explicit_destination if {
	payload := {
		"tool": "argocd",
		"operation": "project",
		"environment": "dev",
		"actions": [{
			"kind": "argocd.project",
			"target": "my-project",
			"risk_tags": [],
			"payload": {"destinations": [{"namespace": "prod", "server": "https://kubernetes.default.svc"}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
