# Generated by AI | 2026-02-25 | Tests for k8s.run_as_root | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_run_as_root if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"run_as_user": 0}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.run_as_root" in d.hits
}

test_allow_non_root_user if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "security_context": {"run_as_user": 1000}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
