# Generated by AI | 2026-02-25 | Tests for k8s.host_namespace_escape | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_host_pid if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"host_pid": true,
				"host_ipc": false,
				"host_network": false,
				"containers": [],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.host_namespace_escape" in d.hits
}

test_deny_host_network if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"host_pid": false,
				"host_ipc": false,
				"host_network": true,
				"containers": [],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"k8s.host_namespace_escape" in d.hits
}

test_allow_no_host_namespaces if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"host_pid": false,
				"host_ipc": false,
				"host_network": false,
				"containers": [],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
