# Generated by AI | 2026-02-25 | Tests for iam.wildcard_principal | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_wildcard_principal_string if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"trust_policy_statements": [{
				"effect": "Allow",
				"principal": "*",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"iam.wildcard_principal" in d.hits
}

test_deny_wildcard_principal_aws_object if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"trust_policy_statements": [{
				"effect": "Allow",
				"principal": {"AWS": "*"},
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"iam.wildcard_principal" in d.hits
}

test_allow_specific_principal if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"trust_policy_statements": [{
				"effect": "Allow",
				"principal": {"AWS": "arn:aws:iam::123456789012:root"},
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
