# Generated by AI | 2026-02-25 | Tests for terraform.sg_open_world | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_sg_open_world_ssh if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"security_group_rules": [{
				"type": "ingress",
				"cidr_blocks": ["0.0.0.0/0"],
				"from_port": 22,
				"to_port": 22,
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"terraform.sg_open_world" in d.hits
}

test_deny_sg_open_world_ipv6 if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"security_group_rules": [{
				"type": "ingress",
				"cidr_blocks": ["::/0"],
				"from_port": 3389,
				"to_port": 3389,
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"terraform.sg_open_world" in d.hits
}

test_allow_sg_private_cidr if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"security_group_rules": [{
				"type": "ingress",
				"cidr_blocks": ["10.0.0.0/8"],
				"from_port": 22,
				"to_port": 22,
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}

test_allow_sg_safe_port if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"security_group_rules": [{
				"type": "ingress",
				"cidr_blocks": ["0.0.0.0/0"],
				"from_port": 443,
				"to_port": 443,
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
