# Generated by AI | 2026-02-25 | Tests for argocd.autosync_prod | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_autosync_in_production if {
	payload := {
		"tool": "argocd",
		"operation": "sync",
		"environment": "production",
		"actions": [{
			"kind": "argocd.sync",
			"target": "my-app",
			"risk_tags": [],
			"payload": {"sync_policy": {"automated": true}},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"argocd.autosync_prod" in d.hits
}

test_allow_autosync_in_dev if {
	payload := {
		"tool": "argocd",
		"operation": "sync",
		"environment": "dev",
		"actions": [{
			"kind": "argocd.sync",
			"target": "my-app",
			"risk_tags": [],
			"payload": {"sync_policy": {"automated": true}},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}

test_allow_manual_sync_in_production if {
	payload := {
		"tool": "argocd",
		"operation": "sync",
		"environment": "production",
		"actions": [{
			"kind": "argocd.sync",
			"target": "my-app",
			"risk_tags": [],
			"payload": {"sync_policy": {"automated": false}},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
