# Generated by AI | 2026-02-24 | OPA bundle migration — deny mass delete test | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_deny_mass_delete_without_breakglass if {
	payload := {
		"tool": "kubectl",
		"operation": "delete",
		"environment": "dev",
		"context": {"environment": "dev"},
		"actions": [
			{
				"kind": "kubectl.delete",
				"target": "default",
				"risk_tags": [],
				"payload": {"resource_count": 12},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	d.reason == "Mass delete actions exceed threshold"
	"ops.mass_delete" in d.hits
}

test_deny_mass_destroy_without_breakglass if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"context": {"environment": "dev"},
		"actions": [
			{
				"kind": "terraform.plan",
				"target": "infra",
				"risk_tags": [],
				"payload": {"destroy_count": 12},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	d.reason == "Mass delete actions exceed threshold"
	"ops.mass_delete" in d.hits
}
