# Generated by AI | 2026-02-25 | Tests for terraform.iam_wildcard_policy | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_iam_wildcard_action if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"iam_policy_statements": [{
				"effect": "Allow",
				"action": "*",
				"resource": "arn:aws:s3:::my-bucket",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"terraform.iam_wildcard_policy" in d.hits
}

test_deny_iam_wildcard_resource if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"iam_policy_statements": [{
				"effect": "Allow",
				"action": "s3:GetObject",
				"resource": "*",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"terraform.iam_wildcard_policy" in d.hits
}

test_allow_iam_scoped_policy if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"iam_policy_statements": [{
				"effect": "Allow",
				"action": "s3:GetObject",
				"resource": "arn:aws:s3:::my-bucket/*",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}

test_allow_iam_deny_statement_with_wildcard if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"iam_policy_statements": [{
				"effect": "Deny",
				"action": "*",
				"resource": "*",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
}
