# Generated by AI | 2026-02-25 | Tests for iam.wildcard_policy | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_deny_iam_action_star_resource_star if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"iam_policy_statements": [{
				"effect": "Allow",
				"action": "*",
				"resource": "*",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not d.allow
	"iam.wildcard_policy" in d.hits
}

test_allow_iam_scoped_action_wildcard_resource if {
	payload := {
		"tool": "terraform",
		"operation": "plan",
		"environment": "dev",
		"actions": [{
			"kind": "terraform.plan",
			"target": "infra",
			"risk_tags": [],
			"payload": {"iam_policy_statements": [{
				"effect": "Allow",
				"action": "s3:*",
				"resource": "*",
			}]},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	not "iam.wildcard_policy" in d.hits
}
