# Generated by AI | 2026-02-24 | Proof test: env-specific mass_delete threshold | environment refactor
package evidra.policy

import rego.v1

# In "production" environment, mass_delete threshold is 3 (from data.json by_env).
# In "dev" environment, falls back to default threshold of 5.
# Deleting 4 resources should DENY in production but ALLOW in dev.

test_env_production_stricter_mass_delete if {
	d := data.evidra.policy.decision with input as {
		"tool": "kubectl",
		"operation": "delete",
		"environment": "production",
		"actions": [
			{
				"kind": "kubectl.delete",
				"target": "default",
				"risk_tags": [],
				"payload": {"resource_count": 4},
			},
		],
	}
	not d.allow
	"ops.mass_delete" in d.hits
}

test_env_dev_allows_same_count if {
	d := data.evidra.policy.decision with input as {
		"tool": "kubectl",
		"operation": "delete",
		"environment": "dev",
		"actions": [
			{
				"kind": "kubectl.delete",
				"target": "default",
				"risk_tags": [],
				"payload": {"resource_count": 4},
			},
		],
	}
	d.allow
	not "ops.mass_delete" in d.hits
}
