# Generated by AI | 2026-02-24 | OPA bundle migration — resolve_param tests | implementation_opa_bundles_all_phases.md
package evidra.policy.defaults

import rego.v1

test_resolve_param_default_env if {
	val := resolve_param("ops.mass_delete.max_deletes") with input as {"environment": ""}
		with data.evidra.data.params as {
			"ops.mass_delete.max_deletes": {"by_env": {"default": 5}},
		}
	val == 5
}

test_resolve_param_specific_env if {
	val := resolve_param("ops.mass_delete.max_deletes") with input as {"environment": "staging"}
		with data.evidra.data.params as {
			"ops.mass_delete.max_deletes": {"by_env": {"default": 5, "staging": 10}},
		}
	val == 10
}

test_resolve_param_missing_env_falls_back_to_default if {
	val := resolve_param("ops.mass_delete.max_deletes") with input as {"environment": "unknown"}
		with data.evidra.data.params as {
			"ops.mass_delete.max_deletes": {"by_env": {"default": 5}},
		}
	val == 5
}

test_resolve_list_param_default if {
	val := resolve_list_param("k8s.namespaces.restricted") with input as {"environment": ""}
		with data.evidra.data.params as {
			"k8s.namespaces.restricted": {"by_env": {"default": ["kube-system"]}},
		}
	val == ["kube-system"]
}

test_resolve_list_param_env_override if {
	val := resolve_list_param("k8s.namespaces.restricted") with input as {"environment": "staging"}
		with data.evidra.data.params as {
			"k8s.namespaces.restricted": {"by_env": {"default": ["kube-system"], "staging": ["kube-system", "monitoring"]}},
		}
	val == ["kube-system", "monitoring"]
}
