# Generated by AI | 2026-02-24 | OPA bundle migration — warn breakglass test | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_warn_breakglass_exposure_lists_hits_and_hints if {
	d := data.evidra.policy.decision with input as {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "prod",
		"source": "cli",
		"actor": {"type": "human"},
		"actions": [
			{
				"kind": "kubectl.apply",
				"target": "kube-system",
				"risk_tags": ["breakglass"],
				"payload": {"namespace": "kube-system"},
			},
		],
	}
	d.allow
	"ops.breakglass_used" in d.hits
	"Use breakglass only for emergencies." in d.hints
	d.reason == "ok"
}
