# Generated by AI | 2026-02-24 | OPA bundle migration — warn autonomous execution test | implementation_opa_bundles_all_phases.md
package evidra.policy

import rego.v1

test_warn_autonomous_execution_collects_hits_and_hints if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actor": {"type": "agent", "origin": "mcp"},
		"actions": [
			{
				"kind": "kubectl.apply",
				"target": "default",
				"risk_tags": [],
				"payload": {"namespace": "default"},
			},
		],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	d.risk_level == "low"
	"ops.autonomous_execution" in d.hits
	"Review changes manually before apply" in d.hints
	d.reason == "ok"
}
