# Generated by AI | 2026-02-25 | Tests for k8s.no_resource_limits | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_warn_missing_limits if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "kubectl.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25"}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	"k8s.no_resource_limits" in d.hits
}

test_warn_missing_memory_limit if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "kubectl.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "resources": {"limits": {"cpu": "100m"}}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	"k8s.no_resource_limits" in d.hits
}

test_no_warn_with_full_limits if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "kubectl.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25", "resources": {"limits": {"cpu": "100m", "memory": "128Mi"}}}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	not "k8s.no_resource_limits" in d.hits
}
