# Generated by AI | 2026-02-25 | Tests for k8s.mutable_image_tag | OPS_V0_SERIOUS_BASELINE_RESEARCH.md
package evidra.policy

import rego.v1

test_warn_latest_tag if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:latest"}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	"k8s.mutable_image_tag" in d.hits
}

test_warn_no_tag if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx"}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	"k8s.mutable_image_tag" in d.hits
}

test_no_warn_pinned_tag if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "nginx:1.25.3"}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	not "k8s.mutable_image_tag" in d.hits
}

test_no_warn_registry_with_port_and_tag if {
	payload := {
		"tool": "kubectl",
		"operation": "apply",
		"environment": "dev",
		"actions": [{
			"kind": "k8s.apply",
			"target": "default",
			"risk_tags": [],
			"payload": {
				"namespace": "default",
				"containers": [{"name": "app", "image": "registry.example.com:5000/myapp:v1.0"}],
				"init_containers": [],
			},
		}],
	}
	d := data.evidra.policy.decision with input as payload
	d.allow
	not "k8s.mutable_image_tag" in d.hits
}
